# Configuration for Free Tier (256MB RAM)
app = 'odontologia-app'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true    # Habilita el apagado automático
  auto_start_machines = true   # Habilita el encendido automático
  min_machines_running = 0     # Permite que baje a 0 máquinas (Costo $0 si no se usa)
  processes = ['app']

# Solo una sección VM y con 256mb
[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "flask db upgrade"