"""Add RIPS fields

Revision ID: 38a517e11521
Revises: d0b4bf1169c0
Create Date: 2025-11-30 09:13:26.249089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a517e11521'
down_revision = 'd0b4bf1169c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_consulta_cups', sa.String(length=20), nullable=True))

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_copago', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_cuota_moderadora', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_comision', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_descuentos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio_periodo', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_final_periodo', sa.Date(), nullable=True))

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primer_nombre', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('segundo_nombre', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('primer_apellido', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('segundo_apellido', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('segundo_apellido')
        batch_op.drop_column('primer_apellido')
        batch_op.drop_column('segundo_nombre')
        batch_op.drop_column('primer_nombre')

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('fecha_final_periodo')
        batch_op.drop_column('fecha_inicio_periodo')
        batch_op.drop_column('valor_descuentos')
        batch_op.drop_column('valor_comision')
        batch_op.drop_column('valor_cuota_moderadora')
        batch_op.drop_column('valor_copago')

    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_column('codigo_consulta_cups')

    # ### end Alembic commands ###
