"""Cambiar tipo de fecha_factura a DateTime con timezone

Revision ID: 7d23b2bf8282
Revises: f80f249ac841
Create Date: 2025-11-17 18:33:05.717855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d23b2bf8282'
down_revision = 'f80f249ac841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.alter_column('fecha_factura',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.alter_column('fecha_factura',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
