"""Hacer paciente_id en Cita nullable

Revision ID: 7f8a3f84d870
Revises: ab1678ab9596
Create Date: 2025-09-12 12:53:55.547669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8a3f84d870'
down_revision = 'ab1678ab9596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('paciente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.alter_column('paciente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
