"""Anadir campos nombre/apellido a Cita como nullable (Intento Limpio)

Revision ID: 82ce97233285
Revises: 7f8a3f84d870
Create Date: 2025-09-12 21:06:08.900154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ce97233285'
down_revision = '7f8a3f84d870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paciente_nombres_str', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paciente_apellidos_str', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_column('paciente_apellidos_str')
        batch_op.drop_column('paciente_nombres_str')

    # ### end Alembic commands ###
