"""Hacer paciente_nombres_str y apellidos_str no nulos con default (Paso 2)"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f9d68a468d'
down_revision = '82ce97233285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        # --- ¡MODIFICACIÓN CLAVE AQUÍ! ---
        # Primero, actualizar las filas existentes que tienen NULL a los valores por defecto
        batch_op.execute("UPDATE cita SET paciente_nombres_str = 'Paciente sin registrar' WHERE paciente_nombres_str IS NULL")
        batch_op.execute("UPDATE cita SET paciente_apellidos_str = '' WHERE paciente_apellidos_str IS NULL")
        
        # Luego, altera las columnas para hacerlas NOT NULL y añadir el server_default
        batch_op.alter_column('paciente_nombres_str',
                               existing_type=sa.VARCHAR(100),
                               nullable=False,
                               existing_server_default=sa.text("''")) # El default se aplica a nuevas filas
        batch_op.alter_column('paciente_apellidos_str',
                               existing_type=sa.VARCHAR(100),
                               nullable=False,
                               existing_server_default=sa.text("''"))
        
        # Si Alembic agregó otras columnas aquí, déjalas sin modificar.
        batch_op.alter_column('paciente_telefono_str',
                               existing_type=sa.VARCHAR(50),
                               nullable=True,
                               existing_server_default=sa.text("''")) # Este es nullable=True, así que no causa NotNullViolation
        # --- FIN MODIFICACIÓN CLAVE ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        # Al hacer downgrade, revertir a nullable=True y quitar el default
        batch_op.alter_column('paciente_apellidos_str',
                               existing_type=sa.VARCHAR(100),
                               nullable=True,
                               existing_server_default=sa.text("''"))
        batch_op.alter_column('paciente_nombres_str',
                               existing_type=sa.VARCHAR(100),
                               nullable=True,
                               existing_server_default=sa.text("''"))

    # Si Alembic detecta otros alter_column aquí, déjalos.
    # ### end Alembic commands ###