"""Agregar campos pre_registro a cita

Revision ID: 84f5e0f38052
Revises: 4f41e2757300
Create Date: 2026-04-02 18:20:23.926875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84f5e0f38052'
down_revision = '4f41e2757300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturas')
    op.drop_table('procedimientos')
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pre_nombres', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pre_apellidos', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pre_telefono', sa.String(length=50), nullable=True))
        batch_op.alter_column('odontologo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('idx_cita_estado', ['estado'], unique=False)
        batch_op.create_index('idx_cita_fecha_odontologo', ['fecha', 'odontologo_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('cita_factura_id_fkey'), type_='foreignkey')
        batch_op.drop_column('diagnostico_relacionado1')
        batch_op.drop_column('tipo_diagnostico_principal')
        batch_op.drop_column('codigo_consulta_cups')
        batch_op.drop_column('paciente_nombres_str')
        batch_op.drop_column('diagnostico_relacionado3')
        batch_op.drop_column('paciente_telefono_str')
        batch_op.drop_column('diagnostico_relacionado2')
        batch_op.drop_column('causa_externa')
        batch_op.drop_column('finalidad_consulta')
        batch_op.drop_column('factura_id')
        batch_op.drop_column('paciente_apellidos_str')
        batch_op.drop_column('diagnostico_principal')

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('sexo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=1),
               existing_nullable=True)
        batch_op.drop_column('antecedentes_quirurgicos')
        batch_op.drop_column('segundo_apellido')
        batch_op.drop_column('codigo_departamento')
        batch_op.drop_column('cepillado')
        batch_op.drop_column('primer_nombre')
        batch_op.drop_column('plan_tratamiento')
        batch_op.drop_column('codigo_aseguradora')
        batch_op.drop_column('farmacologicos')
        batch_op.drop_column('telefono_responsable')
        batch_op.drop_column('referido_por')
        batch_op.drop_column('tipo_afiliado')
        batch_op.drop_column('imagen_2')
        batch_op.drop_column('municipio')
        batch_op.drop_column('nombre_responsable')
        batch_op.drop_column('tipo_vinculacion_rips')
        batch_op.drop_column('antecedentes_familiares')
        batch_op.drop_column('genero_rips')
        batch_op.drop_column('parentesco')
        batch_op.drop_column('departamento')
        batch_op.drop_column('habitos')
        batch_op.drop_column('pais_residencia')
        batch_op.drop_column('primer_apellido')
        batch_op.drop_column('tipo_documento_rips')
        batch_op.drop_column('antecedentes_hemorragicos')
        batch_op.drop_column('aseguradora')
        batch_op.drop_column('reaccion_medicamentos')
        batch_op.drop_column('genero')
        batch_op.drop_column('zona_residencia')
        batch_op.drop_column('imagen_1')
        batch_op.drop_column('tipo_usuario_rips')
        batch_op.drop_column('estado_civil')
        batch_op.drop_column('antecedentes_personales')
        batch_op.drop_column('ocupacion')
        batch_op.drop_column('ultima_visita_odontologo')
        batch_op.drop_column('codigo_municipio')
        batch_op.drop_column('tipo_vinculacion')
        batch_op.drop_column('examen_fisico')
        batch_op.drop_column('segundo_nombre')

    with op.batch_alter_table('pagos_unificados', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_pagos_es_rapido'))
        batch_op.drop_index(batch_op.f('idx_pagos_fecha'))
        batch_op.drop_index(batch_op.f('idx_pagos_paciente_id'))
        batch_op.drop_index(batch_op.f('idx_pagos_usuario_id'))
        batch_op.drop_constraint(batch_op.f('pagos_unificados_paciente_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'paciente', ['paciente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos_unificados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pagos_unificados_paciente_id_fkey'), 'paciente', ['paciente_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_pagos_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pagos_paciente_id'), ['paciente_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pagos_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('idx_pagos_es_rapido'), ['es_rapido'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segundo_nombre', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('examen_fisico', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_vinculacion', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigo_municipio', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ultima_visita_odontologo', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ocupacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('antecedentes_personales', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estado_civil', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_usuario_rips', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imagen_1', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zona_residencia', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('genero', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reaccion_medicamentos', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('aseguradora', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('antecedentes_hemorragicos', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_documento_rips', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('primer_apellido', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pais_residencia', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('habitos', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('departamento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parentesco', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('genero_rips', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('antecedentes_familiares', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_vinculacion_rips', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre_responsable', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('municipio', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imagen_2', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_afiliado', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('referido_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('telefono_responsable', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('farmacologicos', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigo_aseguradora', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('plan_tratamiento', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('primer_nombre', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cepillado', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigo_departamento', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('segundo_apellido', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('antecedentes_quirurgicos', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('sexo',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnostico_principal', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('paciente_apellidos_str', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('finalidad_consulta', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('causa_externa', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('diagnostico_relacionado2', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('paciente_telefono_str', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('diagnostico_relacionado3', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('paciente_nombres_str', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigo_consulta_cups', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_diagnostico_principal', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('diagnostico_relacionado1', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('cita_factura_id_fkey'), 'facturas', ['factura_id'], ['id'])
        batch_op.drop_index('idx_cita_fecha_odontologo')
        batch_op.drop_index('idx_cita_estado')
        batch_op.alter_column('odontologo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('pre_telefono')
        batch_op.drop_column('pre_apellidos')
        batch_op.drop_column('pre_nombres')

    op.create_table('procedimientos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cita_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo_cups', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('diagnostico_cie10', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], name=op.f('procedimientos_cita_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procedimientos_pkey'))
    )
    op.create_table('facturas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero_factura', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('fecha_factura', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('valor_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_copago', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_cuota_moderadora', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_comision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('valor_descuentos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio_periodo', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_final_periodo', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name=op.f('facturas_paciente_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('facturas_pkey')),
    sa.UniqueConstraint('numero_factura', name=op.f('facturas_numero_factura_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
