"""Agregar tabla pagos_paciente

Revision ID: 88cae940cc53
Revises: bd64bf9bcc10
Create Date: 2026-03-01 11:53:14.006620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cae940cc53'
down_revision = 'bd64bf9bcc10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos_paciente', schema=None) as batch_op:
        batch_op.alter_column('monto',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_table_comment(
        existing_comment='"Pagos y abonos realizados por pacientes"'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos_paciente', schema=None) as batch_op:
        batch_op.create_table_comment(
        '"Pagos y abonos realizados por pacientes"',
        existing_comment=None
    )
        batch_op.alter_column('monto',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
