"""agregando relacion cita odontologo

Revision ID: bd64bf9bcc10
Revises: dd9ba02f5937
Create Date: 2025-12-20 21:35:44.228012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd64bf9bcc10'
down_revision = 'dd9ba02f5937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odontologo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['odontologo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('odontologo_id')

    # ### end Alembic commands ###
