"""Anadir campo telefono a Cita

Revision ID: bda89be5983a
Revises: 82f9d68a468d
Create Date: 2025-09-12 22:22:20.301183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda89be5983a'
down_revision = '82f9d68a468d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paciente_telefono_str', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_column('paciente_telefono_str')

    # ### end Alembic commands ###
