"""Add imagen_perfil_url to Paciente

Revision ID: c84504fc25e1
Revises: bda89be5983a
Create Date: 2025-10-19 08:49:28.563733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84504fc25e1'
down_revision = 'bda89be5983a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_perfil_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('imagen_perfil_url')

    # ### end Alembic commands ###
