"""Crear tablas facturas y procedimientos en PostgreSQL local

Revision ID: cc20ab3ac43c
Revises: 7d23b2bf8282
Create Date: 2025-11-17 22:18:13.532898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc20ab3ac43c'
down_revision = '7d23b2bf8282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cups_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_username', sa.String(length=150), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_model', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=True),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('barrio', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('aseguradora', sa.String(length=100), nullable=True),
    sa.Column('tipo_vinculacion', sa.String(length=50), nullable=True),
    sa.Column('ocupacion', sa.String(length=100), nullable=True),
    sa.Column('referido_por', sa.String(length=100), nullable=True),
    sa.Column('nombre_responsable', sa.String(length=100), nullable=True),
    sa.Column('telefono_responsable', sa.String(length=50), nullable=True),
    sa.Column('parentesco', sa.String(length=50), nullable=True),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('enfermedad_actual', sa.Text(), nullable=True),
    sa.Column('antecedentes_personales', sa.Text(), nullable=True),
    sa.Column('antecedentes_familiares', sa.Text(), nullable=True),
    sa.Column('antecedentes_quirurgicos', sa.Text(), nullable=True),
    sa.Column('antecedentes_hemorragicos', sa.Text(), nullable=True),
    sa.Column('farmacologicos', sa.Text(), nullable=True),
    sa.Column('reaccion_medicamentos', sa.Text(), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('habitos', sa.Text(), nullable=True),
    sa.Column('cepillado', sa.Text(), nullable=True),
    sa.Column('examen_fisico', sa.Text(), nullable=True),
    sa.Column('ultima_visita_odontologo', sa.Text(), nullable=True),
    sa.Column('plan_tratamiento', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('imagen_1', sa.String(length=200), nullable=True),
    sa.Column('imagen_2', sa.String(length=200), nullable=True),
    sa.Column('dentigrama_canvas', sa.String(length=255), nullable=True),
    sa.Column('odontologo_id', sa.Integer(), nullable=False),
    sa.Column('imagen_perfil_url', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['odontologo_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paciente_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('evolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=20), nullable=False),
    sa.Column('fecha_factura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('paciente_nombres_str', sa.String(length=100), nullable=False),
    sa.Column('paciente_apellidos_str', sa.String(length=100), nullable=False),
    sa.Column('paciente_telefono_str', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('doctor', sa.String(length=100), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cita_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('procedimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=False),
    sa.Column('codigo_cups', sa.String(length=20), nullable=False),
    sa.Column('diagnostico_cie10', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedimientos')
    with op.batch_alter_table('cita', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cita_is_deleted'))

    op.drop_table('cita')
    op.drop_table('facturas')
    op.drop_table('evolucion')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paciente_is_deleted'))

    op.drop_table('paciente')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))

    op.drop_table('audit_log')
    op.drop_table('usuarios')
    op.drop_table('cups_codes')
    # ### end Alembic commands ###
