"""Add tipo_afiliado to Paciente

Revision ID: d0b4bf1169c0
Revises: e75637117faf
Create Date: 2025-11-26 22:55:23.776147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b4bf1169c0'
down_revision = 'e75637117faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_afiliado', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('tipo_afiliado')

    # ### end Alembic commands ###
