"""Add Procedimiento model

Revision ID: dacb59fcaa0a
Revises: 202d222ba8da
Create Date: 2025-11-16 20:48:30.659180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacb59fcaa0a'
down_revision = '202d222ba8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=False),
    sa.Column('codigo_cups', sa.String(length=20), nullable=False),
    sa.Column('diagnostico_cie10', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedimientos')
    # ### end Alembic commands ###
