
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column # Necesario para el UPDATE


# revision identifiers, used by Alembic.
revision = 'dd9ba02f5937'
down_revision = 'dedeb2aad706'
branch_labels = None
depends_on = None


# La función upgrade() con el cambio
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # PASO 1: CREAR TABLA solicitudes_pago_manual (SIN CAMBIOS)
    op.create_table('solicitudes_pago_manual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('plan_nombre', sa.String(length=80), nullable=False),
    sa.Column('monto_cop', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.Column('comprobante_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # PASO 2: AÑADIR LA COLUMNA precio_cop COMO NULLABLE (para que no falle)
    with op.batch_alter_table('planes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_cop', sa.Integer(), nullable=True)) # <--- ¡AQUÍ ESTÁ EL CAMBIO CLAVE!

    # PASO 3: INSERTAR DATOS A LAS FILAS EXISTENTES (UPDATE)
    planes_table = table('planes',
                         column('nombre', sa.String),
                         column('precio_cop', sa.Integer))
    
    # Asigna el valor en COP a los planes existentes
    op.execute(
        planes_table.update().where(planes_table.c.nombre == 'trial').values(precio_cop=0)
    )
    op.execute(
        planes_table.update().where(planes_table.c.nombre == 'basico').values(precio_cop=20000)
    )
    op.execute(
        planes_table.update().where(planes_table.c.nombre == 'profesional').values(precio_cop=28000)
    )

    # PASO 4: CAMBIAR LA COLUMNA A NOT NULL (Ahora es seguro porque no hay nulos)
    with op.batch_alter_table('planes', schema=None) as batch_op:
        batch_op.alter_column('precio_cop',
                              existing_type=sa.Integer(),
                              nullable=False,
                              existing_nullable=True,
                              server_default='0') # Opcional: poner un default permanente si lo deseas

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planes', schema=None) as batch_op:
        batch_op.drop_column('precio_cop')

    op.drop_table('solicitudes_pago_manual')
    # ### end Alembic commands ###
