"""Add plan system tables

Revision ID: dedeb2aad706
Revises: 38a517e11521
Create Date: 2025-12-02 22:09:32.411691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedeb2aad706'
down_revision = '38a517e11521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('precio_mensual', sa.Float(), nullable=False),
    sa.Column('limite_pacientes_diario', sa.Integer(), nullable=False),
    sa.Column('limite_pacientes_diario_primeros_7_dias', sa.Integer(), nullable=False),
    sa.Column('duracion_trial_dias', sa.Integer(), nullable=False),
    sa.Column('caracteristicas', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('auditoria_accesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_email', sa.String(length=120), nullable=True),
    sa.Column('tipo_accion', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('recurso_tipo', sa.String(length=50), nullable=True),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadatos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria_accesos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_accesos_timestamp'), ['timestamp'], unique=False)

    op.create_table('limites_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('contador_pacientes', sa.Integer(), nullable=False),
    sa.Column('limite_actual', sa.Integer(), nullable=False),
    sa.Column('es_dia_trial', sa.Boolean(), nullable=False),
    sa.Column('dia_numero_trial', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'fecha', name='uq_usuario_fecha')
    )
    op.create_table('usuarios_planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('fecha_cancelacion', sa.DateTime(), nullable=True),
    sa.Column('es_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_dias_restantes', sa.Integer(), nullable=True),
    sa.Column('trial_pacientes_primeros_7_dias', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios_planes', schema=None) as batch_op:
        batch_op.create_index('idx_usuario_fecha_fin', ['usuario_id', 'fecha_fin'], unique=False)
        batch_op.create_index('idx_usuario_plan_activo', ['usuario_id', 'estado'], unique=False)

    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_plan_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('id_transaccion', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('periodo_inicio', sa.DateTime(), nullable=False),
    sa.Column('periodo_fin', sa.DateTime(), nullable=False),
    sa.Column('metadatos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_plan_id'], ['usuarios_planes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_transaccion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    with op.batch_alter_table('usuarios_planes', schema=None) as batch_op:
        batch_op.drop_index('idx_usuario_plan_activo')
        batch_op.drop_index('idx_usuario_fecha_fin')

    op.drop_table('usuarios_planes')
    op.drop_table('limites_diarios')
    with op.batch_alter_table('auditoria_accesos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_accesos_timestamp'))

    op.drop_table('auditoria_accesos')
    op.drop_table('planes')
    # ### end Alembic commands ###
